### ISSUE TITLE
3.0.1 version removed the stale label on some issues

### ISSUE THREAD

**Issue by Gustry** [actions/stale#67]
I upgraded to 3.0.1 yesterday, but it seems the run from this morning removed the label from some tickets:

https://github.com/3liz/lizmap-web-client/issues/727

Is-it because the bot didn't recognized it was a custom GitHub token in the action?
Related to #21 ?

**Comment by hross** [comment]
yes this is related. adding a comment will reset the stale counter, so in this case you have 365 more days until the issue gets marked stale. incidentally your close days is not additive to stale (I wonder if it should be) so the issue will get closed immediately after it gets marked stale with the configuration you currently have set up.

**Comment by hross** [comment]
you can turn the behavior off with the `remove-stale-when-updated` flag

**Comment by Gustry** [comment]
Thanks, I noticed the weird behaviour this morning : https://github.com/3liz/lizmap-web-client/issues/392
The bot is confused :)

Well, I wanted to the behaviour `remove-stale-when-updated` so when a user comments, it resets the counter. But this should have an exception for the current token used for the bot.

**Comment by hross** [comment]
Sorry about the bug here. I fixed this behavior here: https://github.com/actions/stale/pull/73

If you use the v3 label in the action you should pick it up automatically next time.

**Comment by hross** [comment]
New release is here and at the v3 tag: https://github.com/actions/stale/releases/tag/v3.0.3

**Comment by DanTup** [comment]
> incidentally your close days is not additive to stale

Can you clarify what this means? It sounds like the close time wouldn't wouldn't be added on to the stale time, though I expected that it would - and the examples have lower close values than stale:

```yaml
        days-before-stale: 30
        days-before-close: 5
```

I'm unsure how I've configured mine now (it's as the sample above) :-)

**Comment by Gustry** [comment]
The workflow ran this morning using version 3.0.4:
https://github.com/3liz/lizmap-web-client/blob/master/.github/workflows/stale_issue.yml

But I can still notice this issue on this ticket:
https://github.com/3liz/lizmap-web-client/issues/1254
The bot added the label but removed it too at the same time.

But not this one:
https://github.com/3liz/lizmap-web-client/issues/1247

**Comment by Gustry** [comment]
I have updated to the latest version 3.0.6, still the same issue:
Example https://github.com/3liz/lizmap-web-client/issues/1601
